authorName: Unknown
experimentName: enas_macro
trialConcurrency: 2
maxExecDuration: 24h
maxTrialNum: 10
#choice: local, remote
trainingServicePlatform: local
#choice: true, false
useAnnotation: false
multiPhase: true
tuner:
  codeDir: ./../../tuners/enas
  classFileName: nni_controller_cifar10.py
  className: ENASTuner
  classArgs:
    macro_str: "macro"

trial:
  command: sh ./script/macro_child.sh
  codeDir: ./
  gpuNum: 1
